In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
TRAIN_DATA_PATH = '../../dataset/train.csv'
TEST_DATA_PATH = '../../dataset/test.csv'
SAMPLE_SUB_PATH = '../../dataset/sample_submission.csv'
X_META_DATA_PATH = '../../dataset/meta/x_feature_info.csv'
Y_META_DATA_PATH = '../../dataset/meta/y_feature_info.csv'
SPEC_DATA_PATH = '../../dataset/meta/y_feature_spec_info.csv'


df_train = pd.read_csv(TRAIN_DATA_PATH)
df_test = pd.read_csv(TEST_DATA_PATH)
df_sample = pd.read_csv(SAMPLE_SUB_PATH)
df_x_meta = pd.read_csv(X_META_DATA_PATH)
df_y_meta = pd.read_csv(Y_META_DATA_PATH)
df_spec = pd.read_csv(SPEC_DATA_PATH)

In [ ]:
def create_anomaly_cols(df, df_spec):
    df_y = df[df_spec['Feature'].values]        # get y cols
    cols_idx = [i for i in range(len(df_y))]

    for i in range(len(df_spec)):
        new_cols = []
        cols_name, y_min, y_max = df_spec.iloc[i]
        check_col = df[cols_name]

        for j in cols_idx:
            if y_min <= check_col[j] <= y_max:
                new_cols.append(j)

        
        cols_idx = new_cols

    new_df = df.copy()
    new_df['label'] = 0
    new_df['label'][cols_idx] = 1
    
    return new_df

def create_separte_anomaly_cols(df, df_spec):
    df_y = df[df_spec['Feature'].values]        # get y cols
    new_df = df.copy()

    for i in range(len(df_spec)):
        cols_idx = [idx for idx in range(len(df_y))]
        new_cols = []

        cols_name, y_min, y_max = df_spec.iloc[i]
        check_col = df[cols_name]

        for j in cols_idx:
            if y_min <= check_col[j] <= y_max:
                new_cols.append(j)

        new_col_name = f"Y_{str(i+1).zfill(2)}_defeated"
        new_df[new_col_name] = 0
        new_df[new_col_name][new_cols] = 1
    
    return new_df

new_df = create_separte_anomaly_cols(df_train, df_spec)
new_df = create_anomaly_cols(new_df, df_spec)
# save
new_df.to_csv("../../dataset/anomaly_cols_train.csv")

In [3]:
# 단계별 누름량 차이, 평균 (2번 제외?)
# 방열재료의 무게 (10, 11(2, 3) 제외 -> 결측치 많음) 무게가 조금 상관성 이씀
# 방열재료의 면적 ()
# 안테나 패드 위치 (평균, 차이 합?)
# 스크류 삽입 깊이 (평균, 차이) -> 평균 - 현재 위치
# 커넥터 핀 치수 (평균, 차이)
# 분당 회전수 (평균, 차이)
# 하우징 PCB 안착부 치수 (평균, 차이)
# 레이돈 치수 (평균, 차이)
# RF SMT 납량 (평균, 차이)
df_train

,ID,X_01,X_02,X_03,X_04,X_05,X_06,X_07,X_08,X_09,...,Y_05,Y_06,Y_07,Y_08,Y_09,Y_10,Y_11,Y_12,Y_13,Y_14
0,TRAIN_00001,70.544,103.320,67.47,1,101.892,74.983,29.45,62.38,245.71,...,29.632,16.083,4.276,-25.381,-25.529,-22.769,23.792,-25.470,-25.409,-25.304
1,TRAIN_00002,69.524,103.321,65.17,1,101.944,72.943,28.73,61.23,233.61,...,33.179,16.736,3.229,-26.619,-26.523,-22.574,24.691,-26.253,-26.497,-26.438
2,TRAIN_00003,72.583,103.320,64.07,1,103.153,72.943,28.81,105.77,272.20,...,31.801,17.080,2.839,-26.238,-26.216,-22.169,24.649,-26.285,-26.215,-26.370
3,TRAIN_00004,71.563,103.320,67.57,1,101.971,77.022,28.92,115.21,255.36,...,34.503,17.143,3.144,-25.426,-25.079,-21.765,24.913,-25.254,-25.021,-25.345
4,TRAIN_00005,69.524,103.320,63.57,1,101.981,70.904,29.68,103.38,241.46,...,32.602,17.569,3.138,-25.376,-25.242,-21.072,25.299,-25.072,-25.195,-24.974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39602,TRAIN_39603,66.465,103.320,62.27,1,103.150,66.825,30.20,77.83,298.05,...,29.194,16.582,3.410,-26.486,-26.581,-22.772,24.261,-26.491,-26.584,-26.580
39603,TRAIN_39604,66.465,103.321,62.77,1,102.021,66.825,29.21,102.25,270.67,...,29.859,15.659,3.406,-27.308,-27.203,-24.674,23.427,-27.250,-27.334,-27.325
39604,TRAIN_39605,68.504,103.320,64.67,1,103.144,68.864,29.96,102.61,198.07,...,24.720,16.823,3.215,-26.502,-26.687,-22.577,24.301,-26.388,-26.425,-26.601
39605,TRAIN_39606,66.465,103.320,63.67,1,102.025,67.845,30.30,112.60,275.52,...,26.412,15.757,4.216,-26.760,-26.634,-24.066,23.305,-26.536,-26.751,-26.635
39606,TRAIN_39607,66.465,103.320,65.67,1,102.004,69.884,30.16,112.90,276.06,...,30.745,16.781,3.307,-26.054,-26.251,-23.257,24.450,-26.224,-26.256,-26.093

In [14]:
# preprocessing
groups = {
    'push':[1, 2, 5, 6], # 단계별 누름량 평균 구하고, 평균, skew, 빼기
    'area':[7, 8, 9], # 방열재료 면적 
    'pad':[14, 15, 16, 17, 18], # 안테나 패드 위치
    'screw1':[19, 10, 21, 22], # 스크류 샆입 깊이
    'pin':[24, 25, 26, 27, 28, 29], # 커넥터 핀 치수
    'screw2':[30, 31, 32, 33], # 스크류 삽입 깊이
    'rot':[34, 35, 36, 37], # 분당 회전수
    'seat':[38, 39, 40], # 안착부 치수
    'radome':[41, 42, 43, 44], # 레이돔 치수
    'RF':[50, 51, 52, 53, 54 ,55, 56]  # RF 납량
}

def make_features(df_features):
    for k, group in groups.items():
        x_group_cols = [f'X_{str(x).zfill(2)}' for x in group]

        df_features[k+'_mean'] = df_features[x_group_cols].mean(axis=1)
        df_features[k+'_sum'] = df_features[x_group_cols].sum(axis=1)
        df_features[k+'_std'] = df_features[x_group_cols].std(axis=1)
        df_features[k+'_skew'] = df_features[x_group_cols].skew(axis=1)
        if not k=='seat' and not k=='area':
            df_features[k+'_kurtosis'] = df_features[x_group_cols].kurtosis(axis=1)
        df_features[k+'_range'] = df_features[x_group_cols].max(axis=1) - df_features[x_group_cols].min(axis=1)

        # mean diff
        for x_col in x_group_cols:
            df_features[k+f'_{x_col}_mean_diff'] = df_features[k+'_mean']-df_features[x_col]

    return df_features

df_tmp = df_train.iloc[:, :-14]
df_train_features = make_features(df_tmp)
df_test_features = make_features(df_test)
df_train_features = pd.concat([df_train_features, df_train.iloc[:, -14:]], axis=1)

df_train_features.to_csv('../../dataset/train_features.csv', index=False)
df_test_features.to_csv('../../dataset/test_features.csv', index=False)

In [20]:
np.argwhere(np.isnan(df_train_features.iloc[:, 1:].values))

array([], shape=(0, 2), dtype=int64)

In [15]:
list(df_test_features.isnull().sum())

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 39608,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 39608,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [7]:
df_train

,ID,X_01,X_02,X_03,X_04,X_05,X_06,X_07,X_08,X_09,...,Y_05,Y_06,Y_07,Y_08,Y_09,Y_10,Y_11,Y_12,Y_13,Y_14
0,TRAIN_00001,70.544,103.320,67.47,1,101.892,74.983,29.45,62.38,245.71,...,29.632,16.083,4.276,-25.381,-25.529,-22.769,23.792,-25.470,-25.409,-25.304
1,TRAIN_00002,69.524,103.321,65.17,1,101.944,72.943,28.73,61.23,233.61,...,33.179,16.736,3.229,-26.619,-26.523,-22.574,24.691,-26.253,-26.497,-26.438
2,TRAIN_00003,72.583,103.320,64.07,1,103.153,72.943,28.81,105.77,272.20,...,31.801,17.080,2.839,-26.238,-26.216,-22.169,24.649,-26.285,-26.215,-26.370
3,TRAIN_00004,71.563,103.320,67.57,1,101.971,77.022,28.92,115.21,255.36,...,34.503,17.143,3.144,-25.426,-25.079,-21.765,24.913,-25.254,-25.021,-25.345
4,TRAIN_00005,69.524,103.320,63.57,1,101.981,70.904,29.68,103.38,241.46,...,32.602,17.569,3.138,-25.376,-25.242,-21.072,25.299,-25.072,-25.195,-24.974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39602,TRAIN_39603,66.465,103.320,62.27,1,103.150,66.825,30.20,77.83,298.05,...,29.194,16.582,3.410,-26.486,-26.581,-22.772,24.261,-26.491,-26.584,-26.580
39603,TRAIN_39604,66.465,103.321,62.77,1,102.021,66.825,29.21,102.25,270.67,...,29.859,15.659,3.406,-27.308,-27.203,-24.674,23.427,-27.250,-27.334,-27.325
39604,TRAIN_39605,68.504,103.320,64.67,1,103.144,68.864,29.96,102.61,198.07,...,24.720,16.823,3.215,-26.502,-26.687,-22.577,24.301,-26.388,-26.425,-26.601
39605,TRAIN_39606,66.465,103.320,63.67,1,102.025,67.845,30.30,112.60,275.52,...,26.412,15.757,4.216,-26.760,-26.634,-24.066,23.305,-26.536,-26.751,-26.635
39606,TRAIN_39607,66.465,103.320,65.67,1,102.004,69.884,30.16,112.90,276.06,...,30.745,16.781,3.307,-26.054,-26.251,-23.257,24.450,-26.224,-26.256,-26.093

In [6]:
groups = {
    'group1'    : [1, 2, 5, 6],                     # 단계별 누름량
    'group2'    : [3, 7, 10, 8, 11, 9],             # 방열재료 n의 무게, 면적
    'group3'    : [12, 13, 14, 15, 16, 17, 18],     # 12: 커넥터 위치, 13: 안테나 패드위치 차이, 나머지 안테나 패드 위치
    'group4'    : [19, 20, 21, 22],                 # n(1~4) 스크류 삽입 깊이   장비1
    'group5'    : [12, 24, 25, 26, 27, 28, 29],     # 12: 커넥터 위치, n(1~6) 핀 치수  
    'group6'    : [30, 31, 32, 33],                 # n(1~4) 스크류 삽입 깊이   장비2
    'group7'    : [34, 35, 36, 37],                 # n(1~4) 스크류 체결 분당 회전수
    'group8'    : [38, 39, 40],                     # 하우징 PCB 안착부 치수
    'group9'    : [41, 42, 43, 44, 45],             # n(1~4) 안테나 레이돔 치수, 마지막은 레이돔 기울기
    'group10'   : [49, 50, 51, 52, 53, 54, 55, 56]  # 실란트 본드, cal 투입 전 대기시간, RF1~7 smt 납 양
}

## Group1 Mean, Diff

In [4]:
def get_group_mean_diff(df, group_num):
    group_cols = [f'X_{str(x).zfill(2)}' for x in group_num]
    df_group = df[group_cols]

In [5]:
group_cols = [f'X_{str(x).zfill(2)}' for x in groups['groups']]
df_group = df_train[group_cols]

NameError: name 'groups' is not defined